monitor.alsa.rules = [
  {
    matches = [
      { device.description = "EDIFIER W820NB经典版" }
      { device.nick = "EDIFIER W820NB经典版" }
      { device.name = "~alsa_card.usb-EDIFIER_W820NB.*" }
    ]
    actions = {
      update-props = {
        priority.session = 10000
        priority.driver = 10000
      }
    }
  }
]
