# : Manager [[[

[mgr]
cwd = { fg = "#dde3ee" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#6da5ff", bg = "#6da5ff" }
marker_cut      = { fg = "#d3e4ff", bg = "#d3e4ff" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a3c9fe", bg = "#a3c9fe" }

# Count
count_copied   = { fg = "#001c38", bg = "#d3e4ff" }
count_cut      = { fg = "#001c38", bg = "#d3e4ff" }
count_selected = { fg = "#00363b", bg = "#a3c9fe" }

# Border
border_symbol = "│"
border_style  = { fg = "#4ed8e7" }

# : ]]]


# : Tabs (New Section) [[[

[tabs]
active    = { fg = "#00363b", bg = "#4ed8e7", bold = true }
inactive  = { fg = "#8af2ff", bg = "#001f23" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#4ed8e7", fg = "#00363b", bold = true }
normal_alt  = { bg = "#3c4758", fg = "#bcc7db" }

# Select mode
select_main = { bg = "#81d3de", fg = "#00363b", bold = true }
select_alt  = { bg = "#3c4758", fg = "#bcc7db" }

# Unset mode
unset_main = { bg = "#a3c9fe", fg = "#00315b", bold = true }
unset_alt  = { bg = "#3c4758", fg = "#bcc7db" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#4ed8e7", bg = "#343943" }
progress_error  = { fg = "#ffb4ab", bg = "#343943" }

# Permissions
perm_type  = { fg = "#298f9d" }
perm_write = { fg = "#0c70fc" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#3a86ff" }
perm_sep   = { fg = "#00d5f0" }

# : ]]]


# : Picker (Renamed from Select) [[[

[pick]
border   = { fg = "#4ed8e7" }
active   = { fg = "#a3c9fe", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#4ed8e7" }
value  = { fg = "#dde3ee" }

# : ]]]


# : Completion (Renamed from Completion) [[[

[cmp]
border = { fg = "#4ed8e7", bg = "#00363b" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#4ed8e7" }
title   = {}
hovered = { fg = "#d3e4ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#343943" }
cand = { fg = "#4ed8e7" }
rest = { fg = "#00363b" }
desc = { fg = "#dde3ee" }
separator = " ▶ "
separator_style = { fg = "#dde3ee" }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#dde3ee" }
run    = { fg = "#dde3ee" }
footer = { fg = "#00363b", bg = "#81d3de" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#a3c9fe" }
title_warn  = { fg = "#4ed8e7" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#dde3ee" },
    { url = "*/", fg = "#4ed8e7" },
]

# : ]]]

