# : Manager [[[

[mgr]
cwd = { fg = "#e6e2dd" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#d9bf6b", bg = "#d9bf6b" }
marker_cut      = { fg = "#eee2bc", bg = "#eee2bc" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#d2c6a1", bg = "#d2c6a1" }

# Count
count_copied   = { fg = "#211b04", bg = "#eee2bc" }
count_cut      = { fg = "#211b04", bg = "#eee2bc" }
count_selected = { fg = "#35301d", bg = "#d2c6a1" }

# Border
border_symbol = "│"
border_style  = { fg = "#d0c6ab" }

# : ]]]


# : Tabs (New Section) [[[

[tabs]
active    = { fg = "#35301d", bg = "#d0c6ab", bold = true }
inactive  = { fg = "#ece2c6", bg = "#201b0a" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#d0c6ab", fg = "#35301d", bold = true }
normal_alt  = { bg = "#484643", fg = "#cac6c1" }

# Select mode
select_main = { bg = "#cdc6b4", fg = "#343024", bold = true }
select_alt  = { bg = "#484643", fg = "#cac6c1" }

# Unset mode
unset_main = { bg = "#d2c6a1", fg = "#373016", bold = true }
unset_alt  = { bg = "#484643", fg = "#cac6c1" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#d0c6ab", bg = "#3b3936" }
progress_error  = { fg = "#ffb4ab", bg = "#3b3936" }

# Permissions
perm_type  = { fg = "#8b7e5d" }
perm_write = { fg = "#938147" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#cfad42" }
perm_sep   = { fg = "#c6a853" }

# : ]]]


# : Picker (Renamed from Select) [[[

[pick]
border   = { fg = "#d0c6ab" }
active   = { fg = "#d2c6a1", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#d0c6ab" }
value  = { fg = "#e6e2dd" }

# : ]]]


# : Completion (Renamed from Completion) [[[

[cmp]
border = { fg = "#d0c6ab", bg = "#35301d" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#d0c6ab" }
title   = {}
hovered = { fg = "#eee2bc", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3b3936" }
cand = { fg = "#d0c6ab" }
rest = { fg = "#35301d" }
desc = { fg = "#e6e2dd" }
separator = " ▶ "
separator_style = { fg = "#e6e2dd" }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e6e2dd" }
run    = { fg = "#e6e2dd" }
footer = { fg = "#343024", bg = "#cdc6b4" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#d2c6a1" }
title_warn  = { fg = "#d0c6ab" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e6e2dd" },
    { url = "*/", fg = "#d0c6ab" },
]

# : ]]]

