# : Manager [[[

[mgr]
cwd = { fg = "#e2e2e2" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#78d38b", bg = "#78d38b" }
marker_cut      = { fg = "#c5eccd", bg = "#c5eccd" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#aad0b2", bg = "#aad0b2" }

# Count
count_copied   = { fg = "#00210f", bg = "#c5eccd" }
count_cut      = { fg = "#00210f", bg = "#c5eccd" }
count_selected = { fg = "#3a3000", bg = "#aad0b2" }

# Border
border_symbol = "│"
border_style  = { fg = "#e2c54b" }

# : ]]]


# : Tabs (New Section) [[[

[tabs]
active    = { fg = "#3a3000", bg = "#e2c54b", bold = true }
inactive  = { fg = "#ffe168", bg = "#221b00" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#e2c54b", fg = "#3a3000", bold = true }
normal_alt  = { bg = "#474747", fg = "#c6c6c6" }

# Select mode
select_main = { bg = "#d2c6a1", fg = "#373016", bold = true }
select_alt  = { bg = "#474747", fg = "#c6c6c6" }

# Unset mode
unset_main = { bg = "#aad0b2", fg = "#153722", bold = true }
unset_alt  = { bg = "#474747", fg = "#c6c6c6" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#e2c54b", bg = "#393939" }
progress_error  = { fg = "#ffb4ab", bg = "#393939" }

# Permissions
perm_type  = { fg = "#938147" }
perm_write = { fg = "#50915e" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#52c66a" }
perm_sep   = { fg = "#cea500" }

# : ]]]


# : Picker (Renamed from Select) [[[

[pick]
border   = { fg = "#e2c54b" }
active   = { fg = "#aad0b2", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#e2c54b" }
value  = { fg = "#e2e2e2" }

# : ]]]


# : Completion (Renamed from Completion) [[[

[cmp]
border = { fg = "#e2c54b", bg = "#3a3000" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#e2c54b" }
title   = {}
hovered = { fg = "#c5eccd", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#393939" }
cand = { fg = "#e2c54b" }
rest = { fg = "#3a3000" }
desc = { fg = "#e2e2e2" }
separator = " ▶ "
separator_style = { fg = "#e2e2e2" }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e2e2e2" }
run    = { fg = "#e2e2e2" }
footer = { fg = "#373016", bg = "#d2c6a1" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#aad0b2" }
title_warn  = { fg = "#e2c54b" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e2e2e2" },
    { url = "*/", fg = "#e2c54b" },
]

# : ]]]

