
[urgency_low]
    background = "#6583A380"
    foreground = "#CCE5FFE6"
    frame_color = "#6583A303"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5

[urgency_normal]
    background = "#3A546B80"
    foreground = "#CCE7FFE6"
    frame_color = "#3A546B03"
    icon = "$HOME/.config/dunst/icons/hyprdots.svg"
    timeout = 5
