# Matugen template for btop

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal:
# "#RRGGBB", "#BW" or "0-255 0-255 0-255".

# Main background must remain empty for terminal transparency.
theme[main_bg]=""
theme[main_fg]="#dfe2ef"
theme[title]="#abc7ff"
theme[hi_fg]="#c0c4eb"
theme[selected_bg]="#abc7ff"
theme[selected_fg]="#002f66"
theme[inactive_fg]="#c3c6d3"
theme[proc_misc]="#cabff8"

theme[cpu_box]="#8d909c"
theme[mem_box]="#8d909c"
theme[net_box]="#8d909c"
theme[proc_box]="#8d909c"
theme[div_line]="#434751"

theme[temp_start]="#c0c4eb"
theme[temp_mid]="#abc7ff"
theme[temp_end]="#ffb4ab"

theme[cpu_start]="#c0c4eb"
theme[cpu_mid]="#abc7ff"
theme[cpu_end]="#ffb4ab"

theme[free_start]="#c0c4eb"
theme[free_mid]=""
theme[free_end]="#404565"

theme[cached_start]="#cabff8"
theme[cached_mid]=""
theme[cached_end]="#484070"

theme[available_start]="#abc7ff"
theme[available_mid]=""
theme[available_end]="#00458f"

theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

theme[download_start]="#c0c4eb"
theme[download_mid]="#abc7ff"
theme[download_end]="#cabff8"

theme[upload_start]="#c0c4eb"
theme[upload_mid]="#abc7ff"
theme[upload_end]="#cabff8"
