# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#dde3ee"

# Title color for boxes
theme[title]="#4ed8e7"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#81d3de"

# Background color of selected item in processes box
theme[selected_bg]="#4ed8e7"

# Foreground color of selected item in processes box
theme[selected_fg]="#00363b"

# Color of inactive/disabled text
theme[inactive_fg]="#bcc7db"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#a3c9fe"

# Cpu box outline color
theme[cpu_box]="#8691a4"

# Memory/disks box outline color
theme[mem_box]="#8691a4"

# Net up/down box outline color
theme[net_box]="#8691a4"

# Processes box outline color
theme[proc_box]="#8691a4"

# Box divider line and small boxes line color
theme[div_line]="#3c4758"

# Temperature graph colors
theme[temp_start]="#81d3de"
theme[temp_mid]="#4ed8e7"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#81d3de"
theme[cpu_mid]="#4ed8e7"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#81d3de"
theme[free_mid]=""
theme[free_end]="#004f56"

# Mem/Disk cached meter
theme[cached_start]="#a3c9fe"
theme[cached_mid]=""
theme[cached_end]="#1e4876"

# Mem/Disk available meter
theme[available_start]="#4ed8e7"
theme[available_mid]=""
theme[available_end]="#004f56"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#81d3de"
theme[download_mid]="#4ed8e7"
theme[download_end]="#a3c9fe"

# Upload graph colors
theme[upload_start]="#81d3de"
theme[upload_mid]="#4ed8e7"
theme[upload_end]="#a3c9fe"
