# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e6e2dd"

# Title color for boxes
theme[title]="#d0c6ab"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#cdc6b4"

# Background color of selected item in processes box
theme[selected_bg]="#d0c6ab"

# Foreground color of selected item in processes box
theme[selected_fg]="#35301d"

# Color of inactive/disabled text
theme[inactive_fg]="#cac6c1"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d2c6a1"

# Cpu box outline color
theme[cpu_box]="#93908c"

# Memory/disks box outline color
theme[mem_box]="#93908c"

# Net up/down box outline color
theme[net_box]="#93908c"

# Processes box outline color
theme[proc_box]="#93908c"

# Box divider line and small boxes line color
theme[div_line]="#484643"

# Temperature graph colors
theme[temp_start]="#cdc6b4"
theme[temp_mid]="#d0c6ab"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#cdc6b4"
theme[cpu_mid]="#d0c6ab"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#cdc6b4"
theme[free_mid]=""
theme[free_end]="#4b4739"

# Mem/Disk cached meter
theme[cached_start]="#d2c6a1"
theme[cached_mid]=""
theme[cached_end]="#4e472a"

# Mem/Disk available meter
theme[available_start]="#d0c6ab"
theme[available_mid]=""
theme[available_end]="#4d4732"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#cdc6b4"
theme[download_mid]="#d0c6ab"
theme[download_end]="#d2c6a1"

# Upload graph colors
theme[upload_start]="#cdc6b4"
theme[upload_mid]="#d0c6ab"
theme[upload_end]="#d2c6a1"
