[ColorScheme]
active_colors=#1b1b1e, #fcf8fc, #f0edf0, #77767f, #e3e1eb, #c7c5cf, #1b1b1e, #1b1b1e, #1b1b1e, #fcf8fc, #fcf8fc, #000000, #262c4c, #ffffff, #5c5d6d, #5c5d6d, #f6f3f6, #fcf8fc, #fcf8fc, #46464e, #46464e
disabled_colors=#46464e, #e3e1eb, #f0edf0, #77767f, #e3e1eb, #c7c5cf, #46464e, #46464e, #46464e, #e3e1eb, #e3e1eb, #000000, #e3e1eb, #46464e, #46464e, #46464e, #e3e1eb, #e3e1eb, #e3e1eb, #46464e, #46464e
inactive_colors=#46464e, #fcf8fc, #f0edf0, #77767f, #e3e1eb, #c7c5cf, #46464e, #46464e, #46464e, #fcf8fc, #fcf8fc, #000000, #5c5d6d, #ffffff, #5c5d6d, #5c5d6d, #f6f3f6, #fcf8fc, #fcf8fc, #46464e, #46464e

[ColorEffects:Disabled]
Color=70,70,78
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=119,118,127
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[Colors:Button]
BackgroundAlternate=240,237,240
BackgroundNormal=252,248,252
DecorationFocus=38,44,76
DecorationHover=38,44,76
ForegroundActive=38,44,76
ForegroundInactive=70,70,78
ForegroundLink=66,35,60
ForegroundNegative=186,26,26
ForegroundNeutral=92,93,109
ForegroundNormal=27,27,30
ForegroundPositive=66,35,60
ForegroundVisited=92,93,109

[Colors:Complementary]
BackgroundAlternate=240,237,240
BackgroundNormal=252,248,252
DecorationFocus=38,44,76
DecorationHover=38,44,76
ForegroundActive=38,44,76
ForegroundInactive=70,70,78
ForegroundLink=66,35,60
ForegroundNegative=186,26,26
ForegroundNeutral=92,93,109
ForegroundNormal=27,27,30
ForegroundPositive=66,35,60
ForegroundVisited=92,93,109

[Colors:Header]
BackgroundAlternate=252,248,252
BackgroundNormal=252,248,252
DecorationFocus=38,44,76
DecorationHover=38,44,76
ForegroundActive=38,44,76
ForegroundInactive=70,70,78
ForegroundLink=66,35,60
ForegroundNegative=186,26,26
ForegroundNeutral=92,93,109
ForegroundNormal=27,27,30
ForegroundPositive=66,35,60
ForegroundVisited=92,93,109

[Colors:Header][Inactive]
BackgroundAlternate=252,248,252
BackgroundNormal=252,248,252
DecorationFocus=38,44,76
DecorationHover=38,44,76
ForegroundActive=38,44,76
ForegroundInactive=70,70,78
ForegroundLink=66,35,60
ForegroundNegative=186,26,26
ForegroundNeutral=92,93,109
ForegroundNormal=27,27,30
ForegroundPositive=66,35,60
ForegroundVisited=92,93,109

[Colors:Selection]
BackgroundAlternate=60,66,100
BackgroundNormal=38,44,76
DecorationFocus=38,44,76
DecorationHover=38,44,76
ForegroundActive=255,255,255
ForegroundInactive=70,70,78
ForegroundLink=66,35,60
ForegroundNegative=186,26,26
ForegroundNeutral=92,93,109
ForegroundNormal=255,255,255
ForegroundPositive=66,35,60
ForegroundVisited=92,93,109

[Colors:Tooltip]
BackgroundAlternate=252,248,252
BackgroundNormal=252,248,252
DecorationFocus=38,44,76
DecorationHover=38,44,76
ForegroundActive=38,44,76
ForegroundInactive=70,70,78
ForegroundLink=66,35,60
ForegroundNegative=186,26,26
ForegroundNeutral=92,93,109
ForegroundNormal=27,27,30
ForegroundPositive=66,35,60
ForegroundVisited=92,93,109

[Colors:View]
BackgroundAlternate=246,243,246
BackgroundNormal=252,248,252
DecorationFocus=38,44,76
DecorationHover=38,44,76
ForegroundActive=38,44,76
ForegroundInactive=70,70,78
ForegroundLink=66,35,60
ForegroundNegative=186,26,26
ForegroundNeutral=92,93,109
ForegroundNormal=27,27,30
ForegroundPositive=66,35,60
ForegroundVisited=92,93,109

[Colors:Window]
BackgroundAlternate=252,248,252
BackgroundNormal=252,248,252
DecorationFocus=38,44,76
DecorationHover=38,44,76
ForegroundActive=38,44,76
ForegroundInactive=70,70,78
ForegroundLink=66,35,60
ForegroundNegative=186,26,26
ForegroundNeutral=92,93,109
ForegroundNormal=27,27,30
ForegroundPositive=66,35,60
ForegroundVisited=92,93,109

[WM]
activeBackground=252,248,252
activeBlend=27,27,30
activeForeground=27,27,30
inactiveBackground=252,248,252
inactiveBlend=70,70,78
inactiveForeground=70,70,78
