cursor #dee2ef
cursor_text_color #bdc7dc

foreground            #dee2ef
background            #0f141c
selection_foreground  #00363d
selection_background  #82d3e2
url_color             #50d7ed

# black
color8   #8791a5
color0   #4c4c4c

# red
color1   #ac8a8c
color9   #c49ea0
# green
color2   #8aac8b
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
color4  #50d7ed
color12 #a39ec4

# magenta
color5   #a8c8ff
color13  #d5e3ff
# cyan
color6   #8aacab
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0
