# Main colors
background            #0f131c
foreground            #dfe2ef
cursor                #dfe2ef
cursor_text_color     #0f131c
selection_background  #404565
selection_foreground  #dee0ff
url_color             #cabff8

# ANSI colors
color0                #0f131c
color1                #ffb4ab
color2                #cabff8
color3                #c0c4eb
color4                #abc7ff
color5                #cabff8
color6                #c0c4eb
color7                #dfe2ef
color8                #434751
color9                #93000a
color10               #484070
color11               #404565
color12               #00458f
color13               #404565
color14               #484070
color15               #c3c6d3

# Starship prompt bubbles
color255              #00458f
color254              #abc7ff
color253              #404565
color252              #c0c4eb
color251              #484070
color250              #cabff8
color249              #93000a
color248              #ffb4ab
color232              #d7e2ff
color233              #002f66
color234              #dee0ff
color235              #292e4d
color236              #e6deff
color237              #322958
color238              #ffdad6
color239              #690005
color240              #d7e2ff
color243              #abc7ff
color244              #ffb4ab
color245              #434751

# UI elements
active_tab_foreground   #002f66
active_tab_background   #abc7ff
inactive_tab_foreground #d7e2ff
inactive_tab_background #00458f
active_border_color     #abc7ff
inactive_border_color   #8d909c

# Marks
mark1_foreground        #001b3f
mark1_background        #d7e2ff
mark2_foreground        #141937
mark2_background        #dee0ff
mark3_foreground        #1c1442
mark3_background        #e6deff
