cursor #dde3ee
cursor_text_color #bcc7db

foreground            #dde3ee
background            #0e141c
selection_foreground  #00363b
selection_background  #81d3de
url_color             #4ed8e7

# black
color8   #8691a4
color0   #4c4c4c

# red
color1   #ac8a8c
color9   #c49ea0
# green
color2   #8aac8b
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
color4  #4ed8e7
color12 #a39ec4

# magenta
color5   #a3c9fe
color13  #d3e4ff
# cyan
color6   #8aacab
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0
