cursor #e9e2d3
cursor_text_color #cfc6ae

foreground            #e9e2d3
background            #16130a
selection_foreground  #3a3000
selection_background  #d8c687
url_color             #f9d849

color0   #16130a
color1   #ff4c38
color2   #61f949
color3   #ffdf38
color4   #ecc623
color5   #735d00
color6   #f9d849
color7   #fffae9
color8   #a19e90
color9   #ff8477
color10  #92ff80
color11  #ffea80
color12  #ffe265
color13  #ffe780
color14  #ffefad
color15  #fffdf5
