cursor #1b1b1e
cursor_text_color #46464e

foreground            #1b1b1e
background            #fcf8fc
selection_foreground  #ffffff
selection_background  #c5c5d7
url_color             #262c4c

color0   #fcf8fc
color1   #793043
color2   #215f2b
color3   #8b6c19
color4   #252c4f
color5   #3c4264
color6   #262c4c
color7   #222223
color8   #bbbbbe
color9   #994c60
color10  #3f8c4b
color11  #a58531
color12  #272e57
color13  #404562
color14  #4a4e62
color15  #bbbbbf
